package expressions

func Select(args Args) Expression              { return newNode(KindSelect, args) }
func From(args Args) Expression                { return newNode(KindFrom, args) }
func Join(args Args) Expression                { return newNode(KindJoin, args) }
func Table(args Args) Expression               { return newNode(KindTable, args) }
func TableAlias(args Args) Expression          { return newNode(KindTableAlias, args) }
func Where(args Args) Expression               { return newNode(KindWhere, args) }
func Group(args Args) Expression               { return newNode(KindGroup, args) }
func Order(args Args) Expression               { return newNode(KindOrder, args) }
func Limit(args Args) Expression               { return newNode(KindLimit, args) }
func Offset(args Args) Expression              { return newNode(KindOffset, args) }
func Tuple(args Args) Expression               { return newNode(KindTuple, args) }
func Block(args Args) Expression               { return newNode(KindBlock, args) }
func With(args Args) Expression                { return newNode(KindWith, args) }
func CTE(args Args) Expression                 { return newNode(KindCTE, args) }
func RecursiveWithSearch(args Args) Expression { return newNode(KindRecursiveWithSearch, args) }
func Union(args Args) Expression               { return newNode(KindUnion, args) }
func Except(args Args) Expression              { return newNode(KindExcept, args) }
func Intersect(args Args) Expression           { return newNode(KindIntersect, args) }
func Subquery(args Args) Expression            { return newNode(KindSubquery, args) }
func Having(args Args) Expression              { return newNode(KindHaving, args) }
func Qualify(args Args) Expression             { return newNode(KindQualify, args) }
func Cube(args Args) Expression                { return newNode(KindCube, args) }
func Rollup(args Args) Expression              { return newNode(KindRollup, args) }
func GroupingSets(args Args) Expression        { return newNode(KindGroupingSets, args) }
func Ordered(args Args) Expression             { return newNode(KindOrdered, args) }
func Distinct(args Args) Expression            { return newNode(KindDistinct, args) }
func Window(args Args) Expression              { return newNode(KindWindow, args) }
func WindowSpec(args Args) Expression          { return newNode(KindWindowSpec, args) }
func Filter(args Args) Expression              { return newNode(KindFilter, args) }
func LimitOptions(args Args) Expression        { return newNode(KindLimitOptions, args) }
func Fetch(args Args) Expression               { return newNode(KindFetch, args) }
func Schema(args Args) Expression              { return newNode(KindSchema, args) }
func Lateral(args Args) Expression             { return newNode(KindLateral, args) }
func Pivot(args Args) Expression               { return newNode(KindPivot, args) }
func Values(args Args) Expression              { return newNode(KindValues, args) }
func ColumnDef(args Args) Expression           { return newNode(KindColumnDef, args) }
